### ISSUE TITLE
Área de widget opcional abaixo do destaque principal

### ISSUE THREAD

**Issue by jpmehl** [redelivre/quizumba#14]
Com o objetivo de colocar banners que destaquem determinados conteudos, como banners

**Comment by eduardozulian** [comment]
Alguma demanda específica pra isso?

**Comment by anapaulabrasa** [comment]
É uma demanda pro projeto da ANA http://agroecologia.redelivre.org.br/
Vamos utilizar banners chamando pras sessões de vídeo e imagens.

**Comment by jacsonp** [comment]
para eu ter uma noção, qual o tema que tem isso mesmo?

**Comment by anapaulabrasa** [comment]
@jacsonp O que mais se assemelha a isso é o uso dos wdgets com banners uniformes no Guarani, como em http://observatoriodopresal.redelivre.org.br/ e em http://plataformadh.org.br/.
Ao meu ver, esse tem que ser um espaço que ao mesmo tempo seja de destaque e de sutileza nesse destaque. Assim, penso que deve haver um tamanho uniforme pro espaço dos banners de no máximo uns 130 px de altura.

**Comment by anapaulabrasa** [comment]
Estou testando o rodapé institucional e tá ficando estranho. Veja print abaixo.
Usei tanto o Image Widget como o de texto, e ambos ficam assim.
A imagem que estou usando de teste tem 903 × 91

![printimagewidget](https://cloud.githubusercontent.com/assets/2422926/9944708/7354054e-5d5f-11e5-8f12-c9a1dfe57bb7.png)
